### PR TITLE
initial attempt at encrypt_phpmcrypt submodule

### PR DESCRIPTION
**Pull request by rgristroph**
Not ready for merging yet -- I need to address the tests.  Putting this up for a PR just to get any comments on the approach.

### CODE REVIEW

**Comment by rlhawk** [comment]
Can you explain the reasoning behind making Composer Manager a dependency for this module?

**Comment by rlhawk** [comment]
Just to throw a monkey wrench into the issue:

For the 7.x-3.x branch of Encrypt, I'm considering abandoning Mcrypt altogether and I think we should think about doing that for D8 also. The better alternative is to use OpenSSL and a modern, secure library like [Defuse](https://github.com/defuse/php-encryption). The advantages to getting “off the island” and going this route are numerous. See [“If You're Typing the Word MCRYPT Into Your PHP Code, You're Doing It Wrong”](https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong) for more information.

**Comment by rgristroph** [comment]
I think going with Defuse or similar would be a good idea.  I'll comment on the issue related to it.

Would we maintain mcrypt as a separate module ?  Perhaps with a Bad Judgement dependency ?  And I guess we'd have to decide if it should be in this modules codebase at all, or completely separate ?

**Comment by rgristroph** [comment]
On the composer_manager dependency -- I don't think it is required, I think I have it there as a mistake.  I'll address that as I re-roll this with tests.

**Comment by nerdstein** [comment]
We've decided to not leverage mcrypt at all, its basicaly dead on the vine. I'm closing.

**Pull request closed without merging**
