### PR TITLE
#72 - use PluginCollection pattern for lazy loading EncryptionMethod …

### PR DESCRIPTION
**Pull request by svendecabooter**
…plugins

### CODE REVIEW

**Comment by nerdstein** [comment]
@rlhawk may want to review this, but it looks good to me

**Comment by rlhawk** [comment]
This looks good generally, but I'm getting an error when saving a new profile. 

```
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" plugin does not exist. in
Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 57 of
/Volumes/Rick/Sites/d8/dev/public/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).
```

The issue seems to be with not having a default encryption method for the plugin collection. I ran into this with Key also and I dealt with it by defining a default for each plugin type. I'm not sure how to deal with it here. Most implementations of plugin collections have defaults. One that doesn't is image styles (since there are no default image effects). That's worth looking at to see what we can learn. If I set a default encryption method, there's no error.

**Comment by svendecabooter** [comment]
The image effects seem to default to an empty array.
I ran into the same error you mentioned, and thought I fixed it in this commit: https://github.com/svendecabooter/encrypt/commit/868a5df12b8ded5df734b09be18737e39b6abc87
Not sure if it's the best fix, but it works well on my installation.

Are you just saving a new encryption profile when this error occurs?

**Comment by svendecabooter** [comment]
Latest commit takes inspiration from the Key module, to allow EncryptionMethod plugins to properly define configuration settings, if they wish to. 

An EncryptionMethod plugin would have to implement EncryptionMethodPluginFormInterface, and provide the necessary methods for building & submitting the configuration form.

TODO:
* Properly document this possibility
* Fix tests that are currently broken
* Review code and functionality to see if it needs to be cleaned up

**Comment by rlhawk** [comment]
Thanks, @svendecabooter! Testing now…

**Comment by rlhawk** [comment]
EncryptionMethodPluginFormInterface is great. Plugins that don't have settings won't need to implement it, similar to Key.

I'm still getting the error, only now I see it when trying to view the add page; it appeared before when submitting the add form. Once again, defining a default encryption method (`protected $encryption_method = 'test_encryption_method';`) fixes it.

The only thing that could be different about our tests is which encryption method plugin we're using. I'm just using the rot13 test method.

**Comment by svendecabooter** [comment]
Hmm i have rebased this branch, but now everything seems messed up and creating conflicts :(

I have cherry-picked the relevant commits in this PR, and opened a new one: https://github.com/d8-contrib-modules/encrypt/pull/103
There it seems to be OK. Sorry for breaking the conversation / work here :(

@rlhawk can you test the issue you're encountering again with https://github.com/d8-contrib-modules/encrypt/pull/103? I can't see any more errors now, and the test doesn't expose them either.

**Pull request closed without merging**
